apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.20.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/platform/helm/cert-manager/values.yaml
    - repoURL: https://github.com/cmcgalliard/2026-oss-summit.git
      targetRevision: try-two
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    - group: cert-manager.io
      kind: ClusterIssuer
      jsonPointers:
        - /status
