---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.55.0"
      helm:
        releaseName: loki
        valueFiles:
          - $values/platform/helm/o11y/loki-values.yaml
    - repoURL: https://github.com/cmcgalliard/2026-oss-summit.git
      targetRevision: try-two
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: o11y
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.24.4"
      helm:
        releaseName: tempo
        valueFiles:
          - $values/platform/helm/o11y/tempo-values.yaml
    - repoURL: https://github.com/cmcgalliard/2026-oss-summit.git
      targetRevision: try-two
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: o11y
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: "10.5.15"
      helm:
        releaseName: grafana
        valueFiles:
          - $values/platform/helm/o11y/grafana-values.yaml
    - repoURL: https://github.com/cmcgalliard/2026-oss-summit.git
      targetRevision: try-two
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: o11y
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
