---
apiVersion: v1
kind: Secret
metadata:
  name: linode-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  credentials: |
    {
      "token": "REPLACE_WITH_OSS_LINODE_API_TOKEN"
    }
